<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mane" ignored="2" name="Test(failed)" tests="2" failures="2" timestamp="30 Jul 2019 04:20:43 GMT" time="0.094" errors="0">
  <testcase name="f2" time="0.009" classname="Testcases.testngclass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Testcases.testngclass.f2(testngclass.java:34)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
  <testcase name="f1" time="0.003" classname="Testcases.testngclass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Testcases.testngclass.f1(testngclass.java:39)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="exceptionTestOne" time="0.0" classname="Testcases.testngclass">
    <ignored/>
  </testcase> <!-- exceptionTestOne -->
  <testcase name="f" time="0.0" classname="Testcases.testngclass">
    <ignored/>
  </testcase> <!-- f -->
</testsuite> <!-- Test(failed) -->
